# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vscode-clone.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGridLayout,
    QHBoxLayout, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QSpacerItem,
    QSplitter, QStackedWidget, QTabWidget, QTreeView,
    QVBoxLayout, QWidget)
import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1109, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(0, 35))
        self.widget.setMaximumSize(QSize(16777215, 35))
        self.widget.setStyleSheet(u"")
        self.horizontalLayout_2 = QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.vscodeLogo = QLabel(self.widget)
        self.vscodeLogo.setObjectName(u"vscodeLogo")
        self.vscodeLogo.setMinimumSize(QSize(34, 34))
        self.vscodeLogo.setMaximumSize(QSize(34, 34))
        self.vscodeLogo.setPixmap(QPixmap(u":/icons/icons/vscode.svg"))
        self.vscodeLogo.setScaledContents(True)
        self.vscodeLogo.setMargin(9)

        self.horizontalLayout_2.addWidget(self.vscodeLogo)

        self.file = QPushButton(self.widget)
        self.file.setObjectName(u"file")
        self.file.setMinimumSize(QSize(40, 34))
        self.file.setMaximumSize(QSize(40, 34))
        font = QFont()
        font.setFamilies([u"Roboto Medium"])
        font.setPointSize(9)
        font.setBold(False)
        self.file.setFont(font)
        self.file.setCheckable(False)
        self.file.setAutoExclusive(False)

        self.horizontalLayout_2.addWidget(self.file)

        self.edit = QPushButton(self.widget)
        self.edit.setObjectName(u"edit")
        self.edit.setMinimumSize(QSize(40, 34))
        self.edit.setMaximumSize(QSize(40, 34))
        self.edit.setFont(font)
        self.edit.setCheckable(False)
        self.edit.setAutoExclusive(False)

        self.horizontalLayout_2.addWidget(self.edit)

        self.selection = QPushButton(self.widget)
        self.selection.setObjectName(u"selection")
        self.selection.setMinimumSize(QSize(65, 34))
        self.selection.setMaximumSize(QSize(65, 34))
        self.selection.setFont(font)
        self.selection.setCheckable(False)
        self.selection.setAutoExclusive(False)

        self.horizontalLayout_2.addWidget(self.selection)

        self.view = QPushButton(self.widget)
        self.view.setObjectName(u"view")
        self.view.setMinimumSize(QSize(40, 34))
        self.view.setMaximumSize(QSize(40, 34))
        self.view.setFont(font)
        self.view.setCheckable(False)
        self.view.setAutoExclusive(False)

        self.horizontalLayout_2.addWidget(self.view)

        self.go = QPushButton(self.widget)
        self.go.setObjectName(u"go")
        self.go.setMinimumSize(QSize(40, 34))
        self.go.setMaximumSize(QSize(40, 34))
        self.go.setFont(font)
        self.go.setCheckable(False)
        self.go.setAutoExclusive(False)

        self.horizontalLayout_2.addWidget(self.go)

        self.run = QPushButton(self.widget)
        self.run.setObjectName(u"run")
        self.run.setMinimumSize(QSize(40, 34))
        self.run.setMaximumSize(QSize(40, 34))
        self.run.setFont(font)
        self.run.setCheckable(False)
        self.run.setAutoExclusive(False)

        self.horizontalLayout_2.addWidget(self.run)

        self.more = QPushButton(self.widget)
        self.more.setObjectName(u"more")
        self.more.setMinimumSize(QSize(40, 34))
        self.more.setMaximumSize(QSize(40, 34))
        font1 = QFont()
        font1.setFamilies([u"Poppins Black"])
        font1.setPointSize(9)
        font1.setBold(True)
        self.more.setFont(font1)
        self.more.setIconSize(QSize(0, 0))
        self.more.setCheckable(False)
        self.more.setAutoExclusive(False)

        self.horizontalLayout_2.addWidget(self.more)

        self.horizontalSpacer_3 = QSpacerItem(30, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_3)

        self.pushButton_8 = QPushButton(self.widget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setMinimumSize(QSize(35, 34))
        self.pushButton_8.setMaximumSize(QSize(35, 34))
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QCursor(Qt.PointingHandCursor))
        icon = QIcon()
        icon.addFile(u":/icons/icons/arrow-left.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setIconSize(QSize(18, 18))

        self.horizontalLayout_2.addWidget(self.pushButton_8)

        self.pushButton_9 = QPushButton(self.widget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setMinimumSize(QSize(35, 34))
        self.pushButton_9.setMaximumSize(QSize(35, 34))
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/arrow-right.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QSize(18, 18))

        self.horizontalLayout_2.addWidget(self.pushButton_9)

        self.horizontalSpacer_4 = QSpacerItem(10, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_4)

        self.pushButton_10 = QPushButton(self.widget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setMinimumSize(QSize(450, 27))
        self.pushButton_10.setMaximumSize(QSize(450, 27))
        font2 = QFont()
        font2.setFamilies([u"Calibri"])
        font2.setPointSize(9)
        font2.setBold(False)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        font2.setKerning(True)
        font2.setStyleStrategy(QFont.PreferDefault)
        self.pushButton_10.setFont(font2)
        self.pushButton_10.setCursor(QCursor(Qt.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u":/icons/icons/search.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_10.setIcon(icon2)
        self.pushButton_10.setIconSize(QSize(16, 16))

        self.horizontalLayout_2.addWidget(self.pushButton_10)

        self.horizontalSpacer_2 = QSpacerItem(0, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)

        self.splitLeft_btn = QPushButton(self.widget)
        self.splitLeft_btn.setObjectName(u"splitLeft_btn")
        self.splitLeft_btn.setMinimumSize(QSize(25, 25))
        self.splitLeft_btn.setMaximumSize(QSize(25, 25))
        self.splitLeft_btn.setFont(font)
        self.splitLeft_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon3 = QIcon()
        icon3.addFile(u":/icons/icons/3.png", QSize(), QIcon.Normal, QIcon.Off)
        self.splitLeft_btn.setIcon(icon3)
        self.splitLeft_btn.setIconSize(QSize(14, 14))
        self.splitLeft_btn.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.splitLeft_btn)

        self.splitDoawn_btn = QPushButton(self.widget)
        self.splitDoawn_btn.setObjectName(u"splitDoawn_btn")
        self.splitDoawn_btn.setMinimumSize(QSize(25, 25))
        self.splitDoawn_btn.setMaximumSize(QSize(25, 25))
        self.splitDoawn_btn.setFont(font)
        self.splitDoawn_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon4 = QIcon()
        icon4.addFile(u":/icons/icons/5.png", QSize(), QIcon.Normal, QIcon.Off)
        self.splitDoawn_btn.setIcon(icon4)
        self.splitDoawn_btn.setIconSize(QSize(14, 14))
        self.splitDoawn_btn.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.splitDoawn_btn)

        self.showSplit_btn = QPushButton(self.widget)
        self.showSplit_btn.setObjectName(u"showSplit_btn")
        self.showSplit_btn.setMinimumSize(QSize(25, 25))
        self.showSplit_btn.setMaximumSize(QSize(25, 25))
        self.showSplit_btn.setFont(font)
        self.showSplit_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon5 = QIcon()
        icon5.addFile(u":/icons/icons/customize-layout.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.showSplit_btn.setIcon(icon5)
        self.showSplit_btn.setIconSize(QSize(14, 14))
        self.showSplit_btn.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.showSplit_btn)

        self.minimizeWindow = QPushButton(self.widget)
        self.minimizeWindow.setObjectName(u"minimizeWindow")
        self.minimizeWindow.setMinimumSize(QSize(45, 34))
        self.minimizeWindow.setMaximumSize(QSize(45, 34))
        icon6 = QIcon()
        icon6.addFile(u":/icons/icons/chrome-minimize.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.minimizeWindow.setIcon(icon6)
        self.minimizeWindow.setFlat(False)

        self.horizontalLayout_2.addWidget(self.minimizeWindow)

        self.maximizeWindow = QPushButton(self.widget)
        self.maximizeWindow.setObjectName(u"maximizeWindow")
        self.maximizeWindow.setMinimumSize(QSize(45, 34))
        self.maximizeWindow.setMaximumSize(QSize(45, 34))
        icon7 = QIcon()
        icon7.addFile(u":/icons/icons/chrome-restore.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon7.addFile(u":/icons/icons/chrome-maximize.svg", QSize(), QIcon.Normal, QIcon.On)
        self.maximizeWindow.setIcon(icon7)
        self.maximizeWindow.setCheckable(True)
        self.maximizeWindow.setFlat(False)

        self.horizontalLayout_2.addWidget(self.maximizeWindow)

        self.closeWindow = QPushButton(self.widget)
        self.closeWindow.setObjectName(u"closeWindow")
        self.closeWindow.setMinimumSize(QSize(45, 34))
        self.closeWindow.setMaximumSize(QSize(45, 34))
        self.closeWindow.setStyleSheet(u"")
        icon8 = QIcon()
        icon8.addFile(u":/icons/icons/chrome-close.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.closeWindow.setIcon(icon8)
        self.closeWindow.setFlat(False)

        self.horizontalLayout_2.addWidget(self.closeWindow)


        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)

        self.widget_3 = QWidget(self.centralwidget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setMinimumSize(QSize(50, 0))
        self.widget_3.setMaximumSize(QSize(50, 16777215))
        self.widget_3.setStyleSheet(u"")
        self.verticalLayout = QVBoxLayout(self.widget_3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.file_btn = QPushButton(self.widget_3)
        self.file_btn.setObjectName(u"file_btn")
        self.file_btn.setMinimumSize(QSize(49, 49))
        self.file_btn.setMaximumSize(QSize(49, 49))
        self.file_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon9 = QIcon()
        icon9.addFile(u":/icons/icons/2.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.file_btn.setIcon(icon9)
        self.file_btn.setIconSize(QSize(25, 25))
        self.file_btn.setCheckable(True)
        self.file_btn.setAutoExclusive(True)
        self.file_btn.setAutoDefault(False)

        self.verticalLayout.addWidget(self.file_btn)

        self.search_btn = QPushButton(self.widget_3)
        self.search_btn.setObjectName(u"search_btn")
        self.search_btn.setMinimumSize(QSize(49, 49))
        self.search_btn.setMaximumSize(QSize(49, 49))
        self.search_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon10 = QIcon()
        icon10.addFile(u":/icons/icons/12.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.search_btn.setIcon(icon10)
        self.search_btn.setIconSize(QSize(25, 25))
        self.search_btn.setCheckable(True)
        self.search_btn.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.search_btn)

        self.sourceControl_btn = QPushButton(self.widget_3)
        self.sourceControl_btn.setObjectName(u"sourceControl_btn")
        self.sourceControl_btn.setMinimumSize(QSize(49, 49))
        self.sourceControl_btn.setMaximumSize(QSize(49, 49))
        self.sourceControl_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon11 = QIcon()
        icon11.addFile(u":/icons/icons/16.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.sourceControl_btn.setIcon(icon11)
        self.sourceControl_btn.setIconSize(QSize(25, 25))
        self.sourceControl_btn.setCheckable(True)
        self.sourceControl_btn.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.sourceControl_btn)

        self.debug_btn = QPushButton(self.widget_3)
        self.debug_btn.setObjectName(u"debug_btn")
        self.debug_btn.setMinimumSize(QSize(49, 49))
        self.debug_btn.setMaximumSize(QSize(49, 49))
        self.debug_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon12 = QIcon()
        icon12.addFile(u":/icons/icons/8.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.debug_btn.setIcon(icon12)
        self.debug_btn.setIconSize(QSize(25, 25))
        self.debug_btn.setCheckable(True)
        self.debug_btn.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.debug_btn)

        self.extensions_btn = QPushButton(self.widget_3)
        self.extensions_btn.setObjectName(u"extensions_btn")
        self.extensions_btn.setMinimumSize(QSize(49, 49))
        self.extensions_btn.setMaximumSize(QSize(49, 49))
        self.extensions_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon13 = QIcon()
        icon13.addFile(u":/icons/icons/10.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.extensions_btn.setIcon(icon13)
        self.extensions_btn.setIconSize(QSize(25, 25))
        self.extensions_btn.setCheckable(True)
        self.extensions_btn.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.extensions_btn)

        self.testing_btn = QPushButton(self.widget_3)
        self.testing_btn.setObjectName(u"testing_btn")
        self.testing_btn.setMinimumSize(QSize(49, 49))
        self.testing_btn.setMaximumSize(QSize(49, 49))
        self.testing_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon14 = QIcon()
        icon14.addFile(u":/icons/icons/6.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.testing_btn.setIcon(icon14)
        self.testing_btn.setIconSize(QSize(25, 25))
        self.testing_btn.setCheckable(True)
        self.testing_btn.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.testing_btn)

        self.verticalSpacer = QSpacerItem(20, 159, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.account_btn = QPushButton(self.widget_3)
        self.account_btn.setObjectName(u"account_btn")
        self.account_btn.setMinimumSize(QSize(49, 49))
        self.account_btn.setMaximumSize(QSize(49, 49))
        self.account_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon15 = QIcon()
        icon15.addFile(u":/icons/icons/4.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.account_btn.setIcon(icon15)
        self.account_btn.setIconSize(QSize(25, 25))

        self.verticalLayout.addWidget(self.account_btn)

        self.settings_btn = QPushButton(self.widget_3)
        self.settings_btn.setObjectName(u"settings_btn")
        self.settings_btn.setMinimumSize(QSize(49, 49))
        self.settings_btn.setMaximumSize(QSize(49, 49))
        self.settings_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon16 = QIcon()
        icon16.addFile(u":/icons/icons/14.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.settings_btn.setIcon(icon16)
        self.settings_btn.setIconSize(QSize(25, 25))

        self.verticalLayout.addWidget(self.settings_btn)


        self.gridLayout.addWidget(self.widget_3, 2, 0, 1, 1)

        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setMinimumSize(QSize(0, 23))
        self.widget_2.setMaximumSize(QSize(16777215, 23))
        self.widget_2.setStyleSheet(u"")

        self.gridLayout.addWidget(self.widget_2, 4, 0, 1, 2)

        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setFrameShape(QFrame.NoFrame)
        self.splitter.setOrientation(Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(1)
        self.splitter.setChildrenCollapsible(True)
        self.SW1 = QStackedWidget(self.splitter)
        self.SW1.setObjectName(u"SW1")
        self.SW1.setMinimumSize(QSize(175, 0))
        self.SW1.setMaximumSize(QSize(1000, 16777215))
        self.SW1.setStyleSheet(u"")
        self.page2 = QWidget()
        self.page2.setObjectName(u"page2")
        self.gridLayout_2 = QGridLayout(self.page2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setContentsMargins(10, 10, 0, 0)
        self.widget_4 = QWidget(self.page2)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setMinimumSize(QSize(0, 25))
        self.widget_4.setMaximumSize(QSize(16777215, 25))
        self.widget_4.setStyleSheet(u"")
        self.horizontalLayout_3 = QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(15, 0, 8, 0)
        self.label = QLabel(self.widget_4)
        self.label.setObjectName(u"label")
        font3 = QFont()
        font3.setFamilies([u"Roboto"])
        font3.setPointSize(8)
        font3.setBold(False)
        self.label.setFont(font3)
        self.label.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.label)

        self.horizontalSpacer_5 = QSpacerItem(333, 18, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_5)

        self.newFile = QPushButton(self.widget_4)
        self.newFile.setObjectName(u"newFile")
        self.newFile.setMinimumSize(QSize(24, 24))
        self.newFile.setMaximumSize(QSize(24, 24))
        self.newFile.setCursor(QCursor(Qt.PointingHandCursor))
        icon17 = QIcon()
        icon17.addFile(u":/icons/icons/new-file.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.newFile.setIcon(icon17)
        self.newFile.setIconSize(QSize(16, 16))
        self.newFile.setFlat(False)

        self.horizontalLayout_3.addWidget(self.newFile)

        self.newFolder = QPushButton(self.widget_4)
        self.newFolder.setObjectName(u"newFolder")
        self.newFolder.setMinimumSize(QSize(24, 24))
        self.newFolder.setMaximumSize(QSize(24, 24))
        self.newFolder.setCursor(QCursor(Qt.PointingHandCursor))
        icon18 = QIcon()
        icon18.addFile(u":/icons/icons/new-folder.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.newFolder.setIcon(icon18)
        self.newFolder.setIconSize(QSize(16, 16))
        self.newFolder.setFlat(False)

        self.horizontalLayout_3.addWidget(self.newFolder)

        self.refresh = QPushButton(self.widget_4)
        self.refresh.setObjectName(u"refresh")
        self.refresh.setMinimumSize(QSize(24, 24))
        self.refresh.setMaximumSize(QSize(24, 24))
        self.refresh.setCursor(QCursor(Qt.PointingHandCursor))
        icon19 = QIcon()
        icon19.addFile(u":/icons/icons/refresh.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.refresh.setIcon(icon19)
        self.refresh.setIconSize(QSize(16, 16))
        self.refresh.setFlat(False)

        self.horizontalLayout_3.addWidget(self.refresh)

        self.collapseAll = QPushButton(self.widget_4)
        self.collapseAll.setObjectName(u"collapseAll")
        self.collapseAll.setMinimumSize(QSize(24, 24))
        self.collapseAll.setMaximumSize(QSize(24, 24))
        self.collapseAll.setCursor(QCursor(Qt.PointingHandCursor))
        icon20 = QIcon()
        icon20.addFile(u":/icons/icons/collapse-all.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.collapseAll.setIcon(icon20)
        self.collapseAll.setIconSize(QSize(16, 16))
        self.collapseAll.setFlat(False)

        self.horizontalLayout_3.addWidget(self.collapseAll)

        self.more1 = QPushButton(self.widget_4)
        self.more1.setObjectName(u"more1")
        self.more1.setMinimumSize(QSize(24, 24))
        self.more1.setMaximumSize(QSize(24, 24))
        self.more1.setCursor(QCursor(Qt.PointingHandCursor))
        icon21 = QIcon()
        icon21.addFile(u":/icons/icons/more.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.more1.setIcon(icon21)
        self.more1.setIconSize(QSize(16, 16))
        self.more1.setFlat(False)

        self.horizontalLayout_3.addWidget(self.more1)


        self.gridLayout_2.addWidget(self.widget_4, 0, 0, 1, 1)

        self.treeView = QTreeView(self.page2)
        self.treeView.setObjectName(u"treeView")

        self.gridLayout_2.addWidget(self.treeView, 1, 0, 1, 1)

        self.SW1.addWidget(self.page2)
        self.page1 = QWidget()
        self.page1.setObjectName(u"page1")
        self.SW1.addWidget(self.page1)
        self.page3 = QWidget()
        self.page3.setObjectName(u"page3")
        self.SW1.addWidget(self.page3)
        self.page4 = QWidget()
        self.page4.setObjectName(u"page4")
        self.SW1.addWidget(self.page4)
        self.page5 = QWidget()
        self.page5.setObjectName(u"page5")
        self.SW1.addWidget(self.page5)
        self.page6 = QWidget()
        self.page6.setObjectName(u"page6")
        self.SW1.addWidget(self.page6)
        self.splitter.addWidget(self.SW1)
        self.widget_5 = QWidget(self.splitter)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setMinimumSize(QSize(0, 0))
        font4 = QFont()
        font4.setUnderline(False)
        font4.setStrikeOut(False)
        font4.setKerning(False)
        self.widget_5.setFont(font4)
        self.widget_5.setStyleSheet(u"")
        self.gridLayout_3 = QGridLayout(self.widget_5)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.splitter_2 = QSplitter(self.widget_5)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setFrameShape(QFrame.NoFrame)
        self.splitter_2.setFrameShadow(QFrame.Plain)
        self.splitter_2.setOrientation(Qt.Vertical)
        self.splitter_2.setOpaqueResize(True)
        self.splitter_2.setHandleWidth(1)
        self.splitter_2.setChildrenCollapsible(True)
        self.SW3 = QWidget(self.splitter_2)
        self.SW3.setObjectName(u"SW3")
        self.SW3.setMinimumSize(QSize(0, 0))
        self.gridLayout_6 = QGridLayout(self.SW3)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.SW3)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setTabsClosable(True)

        self.gridLayout_6.addWidget(self.tabWidget, 0, 0, 1, 1)

        # self.floatableWidget = QWidget(self.SW3)
        self.floatableWidget = QWidget(self)





        self.floatableWidget.setObjectName(u"floatableWidget")
        self.floatableWidget.setMinimumSize(QSize(95, 26))
        self.floatableWidget.setMaximumSize(QSize(95, 26))
        self.horizontalLayout_9 = QHBoxLayout(self.floatableWidget)
        self.horizontalLayout_9.setSpacing(3)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.widget_10 = QWidget(self.floatableWidget)
        self.widget_10.setObjectName(u"widget_10")
        self.widget_10.setMinimumSize(QSize(38, 25))
        self.widget_10.setMaximumSize(QSize(38, 25))
        self.horizontalLayout_8 = QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.run_btn = QPushButton(self.widget_10)
        self.run_btn.setObjectName(u"run_btn")
        self.run_btn.setMinimumSize(QSize(20, 25))
        self.run_btn.setMaximumSize(QSize(20, 25))
        self.run_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon22 = QIcon()
        icon22.addFile(u":/icons/icons/run.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.run_btn.setIcon(icon22)
        self.run_btn.setIconSize(QSize(20, 20))

        self.horizontalLayout_8.addWidget(self.run_btn)

        self.runDebug_btn = QPushButton(self.widget_10)
        self.runDebug_btn.setObjectName(u"runDebug_btn")
        self.runDebug_btn.setMinimumSize(QSize(20, 25))
        self.runDebug_btn.setMaximumSize(QSize(20, 25))
        self.runDebug_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon23 = QIcon()
        icon23.addFile(u":/icons/icons/chevron-down.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.runDebug_btn.setIcon(icon23)
        self.runDebug_btn.setIconSize(QSize(12, 12))

        self.horizontalLayout_8.addWidget(self.runDebug_btn)


        self.horizontalLayout_9.addWidget(self.widget_10)

        self.splitTerminal1 = QPushButton(self.floatableWidget)
        self.splitTerminal1.setObjectName(u"splitTerminal1")
        self.splitTerminal1.setMinimumSize(QSize(25, 25))
        self.splitTerminal1.setMaximumSize(QSize(25, 25))
        self.splitTerminal1.setCursor(QCursor(Qt.PointingHandCursor))
        icon24 = QIcon()
        icon24.addFile(u":/icons/icons/split-horizontal.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.splitTerminal1.setIcon(icon24)
        self.splitTerminal1.setIconSize(QSize(16, 16))

        self.horizontalLayout_9.addWidget(self.splitTerminal1)

        self.moreActions3_btn = QPushButton(self.floatableWidget)
        self.moreActions3_btn.setObjectName(u"moreActions3_btn")
        self.moreActions3_btn.setMinimumSize(QSize(25, 25))
        self.moreActions3_btn.setMaximumSize(QSize(25, 25))
        self.moreActions3_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.moreActions3_btn.setIcon(icon21)
        self.moreActions3_btn.setIconSize(QSize(16, 16))

        self.horizontalLayout_9.addWidget(self.moreActions3_btn)


        # self.gridLayout_6.addWidget(self.floatableWidget, 1, 0, 1, 1)

        self.splitter_2.addWidget(self.SW3)
        self.SW2 = QWidget(self.splitter_2)
        self.SW2.setObjectName(u"SW2")
        self.SW2.setMinimumSize(QSize(0, 80))
        self.SW2.setMaximumSize(QSize(16777215, 620))
        self.gridLayout_4 = QGridLayout(self.SW2)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.widget_6 = QWidget(self.SW2)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setMinimumSize(QSize(0, 40))
        self.widget_6.setMaximumSize(QSize(16777215, 40))
        self.widget_6.setStyleSheet(u"")
        self.horizontalLayout = QHBoxLayout(self.widget_6)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.problems_btn = QPushButton(self.widget_6)
        self.problems_btn.setObjectName(u"problems_btn")
        self.problems_btn.setMinimumSize(QSize(70, 30))
        self.problems_btn.setMaximumSize(QSize(70, 30))
        font5 = QFont()
        font5.setFamilies([u"Roboto"])
        font5.setPointSize(9)
        font5.setBold(False)
        font5.setUnderline(False)
        font5.setStrikeOut(False)
        font5.setKerning(False)
        self.problems_btn.setFont(font5)
        self.problems_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.problems_btn.setCheckable(True)
        self.problems_btn.setAutoExclusive(True)

        self.horizontalLayout.addWidget(self.problems_btn)

        self.output_btn = QPushButton(self.widget_6)
        self.output_btn.setObjectName(u"output_btn")
        self.output_btn.setMinimumSize(QSize(55, 30))
        self.output_btn.setMaximumSize(QSize(55, 30))
        self.output_btn.setFont(font5)
        self.output_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.output_btn.setCheckable(True)
        self.output_btn.setAutoExclusive(True)

        self.horizontalLayout.addWidget(self.output_btn)

        self.debugCpnsole_btn = QPushButton(self.widget_6)
        self.debugCpnsole_btn.setObjectName(u"debugCpnsole_btn")
        self.debugCpnsole_btn.setMinimumSize(QSize(100, 30))
        self.debugCpnsole_btn.setMaximumSize(QSize(100, 30))
        self.debugCpnsole_btn.setFont(font5)
        self.debugCpnsole_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.debugCpnsole_btn.setCheckable(True)
        self.debugCpnsole_btn.setAutoExclusive(True)

        self.horizontalLayout.addWidget(self.debugCpnsole_btn)

        self.ports_btn = QPushButton(self.widget_6)
        self.ports_btn.setObjectName(u"ports_btn")
        self.ports_btn.setMinimumSize(QSize(45, 30))
        self.ports_btn.setMaximumSize(QSize(45, 30))
        self.ports_btn.setFont(font5)
        self.ports_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.ports_btn.setCheckable(True)
        self.ports_btn.setAutoExclusive(True)

        self.horizontalLayout.addWidget(self.ports_btn)

        self.terminal_btn = QPushButton(self.widget_6)
        self.terminal_btn.setObjectName(u"terminal_btn")
        self.terminal_btn.setMinimumSize(QSize(65, 30))
        self.terminal_btn.setMaximumSize(QSize(65, 30))
        self.terminal_btn.setFont(font5)
        self.terminal_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.terminal_btn.setCheckable(True)
        self.terminal_btn.setAutoExclusive(True)

        self.horizontalLayout.addWidget(self.terminal_btn)

        self.horizontalSpacer = QSpacerItem(75, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.terminalStackedWidget = QStackedWidget(self.widget_6)
        self.terminalStackedWidget.setObjectName(u"terminalStackedWidget")
        self.terminalStackedWidget.setMinimumSize(QSize(400, 40))
        self.terminalStackedWidget.setMaximumSize(QSize(400, 40))
        self.terminalStackedWidget.setStyleSheet(u"")
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.gridLayout_5 = QGridLayout(self.page_5)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setHorizontalSpacing(5)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_6 = QSpacerItem(188, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_5.addItem(self.horizontalSpacer_6, 0, 0, 1, 1)

        self.processId_btn = QPushButton(self.page_5)
        self.processId_btn.setObjectName(u"processId_btn")
        self.processId_btn.setMinimumSize(QSize(60, 25))
        self.processId_btn.setMaximumSize(QSize(60, 25))
        font6 = QFont()
        font6.setFamilies([u"Roboto"])
        font6.setPointSize(8)
        font6.setUnderline(False)
        font6.setStrikeOut(False)
        font6.setKerning(False)
        self.processId_btn.setFont(font6)
        self.processId_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon25 = QIcon()
        icon25.addFile(u":/icons/icons/server-process.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.processId_btn.setIcon(icon25)
        self.processId_btn.setIconSize(QSize(16, 16))

        self.gridLayout_5.addWidget(self.processId_btn, 0, 1, 1, 1)

        self.widget_7 = QWidget(self.page_5)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setMinimumSize(QSize(38, 25))
        self.widget_7.setMaximumSize(QSize(38, 25))
        self.horizontalLayout_4 = QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.addTerminal_btn = QPushButton(self.widget_7)
        self.addTerminal_btn.setObjectName(u"addTerminal_btn")
        self.addTerminal_btn.setMinimumSize(QSize(20, 25))
        self.addTerminal_btn.setMaximumSize(QSize(20, 25))
        self.addTerminal_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon26 = QIcon()
        icon26.addFile(u":/icons/icons/add.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.addTerminal_btn.setIcon(icon26)
        self.addTerminal_btn.setIconSize(QSize(16, 16))

        self.horizontalLayout_4.addWidget(self.addTerminal_btn)

        self.launchProfile_btn = QPushButton(self.widget_7)
        self.launchProfile_btn.setObjectName(u"launchProfile_btn")
        self.launchProfile_btn.setMinimumSize(QSize(20, 25))
        self.launchProfile_btn.setMaximumSize(QSize(20, 25))
        self.launchProfile_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.launchProfile_btn.setIcon(icon23)
        self.launchProfile_btn.setIconSize(QSize(12, 12))

        self.horizontalLayout_4.addWidget(self.launchProfile_btn)


        self.gridLayout_5.addWidget(self.widget_7, 0, 2, 1, 1)

        self.splitTerminal = QPushButton(self.page_5)
        self.splitTerminal.setObjectName(u"splitTerminal")
        self.splitTerminal.setMinimumSize(QSize(25, 25))
        self.splitTerminal.setMaximumSize(QSize(25, 25))
        self.splitTerminal.setCursor(QCursor(Qt.PointingHandCursor))
        self.splitTerminal.setIcon(icon24)
        self.splitTerminal.setIconSize(QSize(16, 16))

        self.gridLayout_5.addWidget(self.splitTerminal, 0, 3, 1, 1)

        self.killTerminal_btn = QPushButton(self.page_5)
        self.killTerminal_btn.setObjectName(u"killTerminal_btn")
        self.killTerminal_btn.setMinimumSize(QSize(25, 25))
        self.killTerminal_btn.setMaximumSize(QSize(25, 25))
        self.killTerminal_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon27 = QIcon()
        icon27.addFile(u":/icons/icons/trash.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.killTerminal_btn.setIcon(icon27)
        self.killTerminal_btn.setIconSize(QSize(16, 16))

        self.gridLayout_5.addWidget(self.killTerminal_btn, 0, 4, 1, 1)

        self.moreActions_btn = QPushButton(self.page_5)
        self.moreActions_btn.setObjectName(u"moreActions_btn")
        self.moreActions_btn.setMinimumSize(QSize(25, 25))
        self.moreActions_btn.setMaximumSize(QSize(25, 25))
        self.moreActions_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.moreActions_btn.setIcon(icon21)
        self.moreActions_btn.setIconSize(QSize(16, 16))

        self.gridLayout_5.addWidget(self.moreActions_btn, 0, 5, 1, 1)

        self.terminalStackedWidget.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.horizontalLayout_5 = QHBoxLayout(self.page_6)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_7 = QSpacerItem(112, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer_7)

        self.lineEdit = QLineEdit(self.page_6)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setMinimumSize(QSize(250, 25))
        self.lineEdit.setMaximumSize(QSize(16777215, 25))

        self.horizontalLayout_5.addWidget(self.lineEdit)

        self.clearConsole_btn = QPushButton(self.page_6)
        self.clearConsole_btn.setObjectName(u"clearConsole_btn")
        self.clearConsole_btn.setMinimumSize(QSize(25, 25))
        self.clearConsole_btn.setMaximumSize(QSize(25, 25))
        self.clearConsole_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon28 = QIcon()
        icon28.addFile(u":/icons/icons/clear-all.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.clearConsole_btn.setIcon(icon28)
        self.clearConsole_btn.setIconSize(QSize(16, 16))

        self.horizontalLayout_5.addWidget(self.clearConsole_btn)

        self.terminalStackedWidget.addWidget(self.page_6)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.horizontalLayout_6 = QHBoxLayout(self.page_7)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_8 = QSpacerItem(122, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer_8)

        self.comboBox = QComboBox(self.page_7)
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setMinimumSize(QSize(200, 25))
        self.comboBox.setMaximumSize(QSize(200, 25))

        self.horizontalLayout_6.addWidget(self.comboBox)

        self.clearConsole2_btn = QPushButton(self.page_7)
        self.clearConsole2_btn.setObjectName(u"clearConsole2_btn")
        self.clearConsole2_btn.setMinimumSize(QSize(25, 25))
        self.clearConsole2_btn.setMaximumSize(QSize(25, 25))
        self.clearConsole2_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.clearConsole2_btn.setIcon(icon28)
        self.clearConsole2_btn.setIconSize(QSize(16, 16))

        self.horizontalLayout_6.addWidget(self.clearConsole2_btn)

        self.lockScroling_btn = QPushButton(self.page_7)
        self.lockScroling_btn.setObjectName(u"lockScroling_btn")
        self.lockScroling_btn.setMinimumSize(QSize(25, 25))
        self.lockScroling_btn.setMaximumSize(QSize(25, 25))
        self.lockScroling_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon29 = QIcon()
        icon29.addFile(u":/icons/icons/lock.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.lockScroling_btn.setIcon(icon29)
        self.lockScroling_btn.setIconSize(QSize(16, 16))

        self.horizontalLayout_6.addWidget(self.lockScroling_btn)

        self.moreActions2_btn = QPushButton(self.page_7)
        self.moreActions2_btn.setObjectName(u"moreActions2_btn")
        self.moreActions2_btn.setMinimumSize(QSize(25, 25))
        self.moreActions2_btn.setMaximumSize(QSize(25, 25))
        self.moreActions2_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.moreActions2_btn.setIcon(icon21)
        self.moreActions2_btn.setIconSize(QSize(16, 16))

        self.horizontalLayout_6.addWidget(self.moreActions2_btn)

        self.terminalStackedWidget.addWidget(self.page_7)
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.horizontalLayout_7 = QHBoxLayout(self.page_8)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_9 = QSpacerItem(72, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_7.addItem(self.horizontalSpacer_9)

        self.lineEdit_2 = QLineEdit(self.page_8)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setMinimumSize(QSize(250, 25))
        self.lineEdit_2.setMaximumSize(QSize(16777215, 25))
        self.lineEdit_2.setClearButtonEnabled(False)

        self.horizontalLayout_7.addWidget(self.lineEdit_2)

        self.collapseAll_btn = QPushButton(self.page_8)
        self.collapseAll_btn.setObjectName(u"collapseAll_btn")
        self.collapseAll_btn.setMinimumSize(QSize(25, 25))
        self.collapseAll_btn.setMaximumSize(QSize(25, 25))
        self.collapseAll_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.collapseAll_btn.setIcon(icon20)
        self.collapseAll_btn.setIconSize(QSize(16, 16))

        self.horizontalLayout_7.addWidget(self.collapseAll_btn)

        self.viewTable_btn = QPushButton(self.page_8)
        self.viewTable_btn.setObjectName(u"viewTable_btn")
        self.viewTable_btn.setMinimumSize(QSize(25, 25))
        self.viewTable_btn.setMaximumSize(QSize(25, 25))
        self.viewTable_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon30 = QIcon()
        icon30.addFile(u":/icons/icons/list-selection.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.viewTable_btn.setIcon(icon30)
        self.viewTable_btn.setIconSize(QSize(16, 16))

        self.horizontalLayout_7.addWidget(self.viewTable_btn)

        self.terminalStackedWidget.addWidget(self.page_8)
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.terminalStackedWidget.addWidget(self.page_9)

        self.horizontalLayout.addWidget(self.terminalStackedWidget)

        self.maximizeTerminal_btn = QPushButton(self.widget_6)
        self.maximizeTerminal_btn.setObjectName(u"maximizeTerminal_btn")
        self.maximizeTerminal_btn.setMinimumSize(QSize(25, 25))
        self.maximizeTerminal_btn.setMaximumSize(QSize(25, 25))
        self.maximizeTerminal_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon31 = QIcon()
        icon31.addFile(u":/icons/icons/chevron-up.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon31.addFile(u":/icons/icons/chevron-down.svg", QSize(), QIcon.Normal, QIcon.On)
        self.maximizeTerminal_btn.setIcon(icon31)
        self.maximizeTerminal_btn.setIconSize(QSize(16, 16))
        self.maximizeTerminal_btn.setCheckable(True)

        self.horizontalLayout.addWidget(self.maximizeTerminal_btn)

        self.exitTerminal_btn = QPushButton(self.widget_6)
        self.exitTerminal_btn.setObjectName(u"exitTerminal_btn")
        self.exitTerminal_btn.setMinimumSize(QSize(25, 25))
        self.exitTerminal_btn.setMaximumSize(QSize(25, 25))
        self.exitTerminal_btn.setCursor(QCursor(Qt.PointingHandCursor))
        icon32 = QIcon()
        icon32.addFile(u":/icons/icons/close.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.exitTerminal_btn.setIcon(icon32)
        self.exitTerminal_btn.setIconSize(QSize(16, 16))

        self.horizontalLayout.addWidget(self.exitTerminal_btn)


        self.gridLayout_4.addWidget(self.widget_6, 0, 0, 1, 1)

        self.stackedWidget_2 = QStackedWidget(self.SW2)
        self.stackedWidget_2.setObjectName(u"stackedWidget_2")
        self.stackedWidget_2.setStyleSheet(u"")
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.stackedWidget_2.addWidget(self.page_4)

        self.gridLayout_4.addWidget(self.stackedWidget_2, 1, 0, 1, 1)

        self.splitter_2.addWidget(self.SW2)

        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)

        self.splitter.addWidget(self.widget_5)

        self.gridLayout.addWidget(self.splitter, 2, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.file_btn.setDefault(False)
        self.SW1.setCurrentIndex(0)
        self.terminalStackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.vscodeLogo.setText("")
        self.file.setText(QCoreApplication.translate("MainWindow", u"File", None))
        self.edit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.selection.setText(QCoreApplication.translate("MainWindow", u"Selection", None))
        self.view.setText(QCoreApplication.translate("MainWindow", u"View", None))
        self.go.setText(QCoreApplication.translate("MainWindow", u"Go", None))
        self.run.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.more.setText(QCoreApplication.translate("MainWindow", u". . .", None))
        self.pushButton_8.setText("")
        self.pushButton_9.setText("")
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"    vscode_clone", None))
        self.splitLeft_btn.setText("")
        self.splitDoawn_btn.setText("")
        self.showSplit_btn.setText("")
        self.minimizeWindow.setText("")
        self.maximizeWindow.setText("")
        self.closeWindow.setText("")
        self.file_btn.setText("")
        self.search_btn.setText("")
        self.sourceControl_btn.setText("")
        self.debug_btn.setText("")
        self.extensions_btn.setText("")
        self.testing_btn.setText("")
        self.account_btn.setText("")
        self.settings_btn.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"EXPLORER : VSCODE_CLONE", None))
        self.newFile.setText("")
        self.newFolder.setText("")
        self.refresh.setText("")
        self.collapseAll.setText("")
        self.more1.setText("")
        self.run_btn.setText("")
        self.runDebug_btn.setText("")
        self.splitTerminal1.setText("")
        self.moreActions3_btn.setText("")
        self.problems_btn.setText(QCoreApplication.translate("MainWindow", u"PROBLEMS", None))
        self.output_btn.setText(QCoreApplication.translate("MainWindow", u"OUTPUT", None))
        self.debugCpnsole_btn.setText(QCoreApplication.translate("MainWindow", u"DEBUG CONSOLE", None))
        self.ports_btn.setText(QCoreApplication.translate("MainWindow", u"PORTS", None))
        self.terminal_btn.setText(QCoreApplication.translate("MainWindow", u"TERMINAL", None))
        self.processId_btn.setText(QCoreApplication.translate("MainWindow", u"Python", None))
        self.addTerminal_btn.setText("")
        self.launchProfile_btn.setText("")
        self.splitTerminal.setText("")
        self.killTerminal_btn.setText("")
        self.moreActions_btn.setText("")
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Filter(e.g text,!exclude)", None))
        self.clearConsole_btn.setText("")
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Tasks", None))

        self.clearConsole2_btn.setText("")
        self.lockScroling_btn.setText("")
        self.moreActions2_btn.setText("")
        self.lineEdit_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Filter(e.g text,!exclude)", None))
        self.collapseAll_btn.setText("")
        self.viewTable_btn.setText("")
        self.maximizeTerminal_btn.setText("")
        self.exitTerminal_btn.setText("")
    # retranslateUi

